{{- range (list .Values.namespaces.airflow .Values.namespaces.ggircs) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Name }}-airflow-scheduler-rolebinding
  labels:
    release: {{ $.Release.Name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cas-provision-job-runner
subjects:
  - kind: ServiceAccount
    name: {{ $.Release.Name }}-scheduler
    namespace: {{ $.Release.Namespace }}

{{ end }}
