{{- range (list .Release.Namespace .Values.namespaces.ggircs .Values.namespaces.ciip .Values.namespaces.cif) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ . }}
  name: {{ $.Release.Name }}-airflow-scheduler-rolebinding
  labels:
    release: {{ $.Release.Name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
{{ include "cas-airflow.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cas-provision-job-runner
subjects:
  - kind: ServiceAccount
    name: {{ $.Release.Name }}-scheduler
    namespace: {{ $.Release.Namespace }}

{{ end }}
