apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "cas-airflow.fullname" . }}-test-email-on-failure
  labels:
{{ include "cas-airflow.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-upgrade,pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
{{ include "cas-airflow.labels" . | indent 14 }}
        spec:
          activeDeadlineSeconds: 600
          restartPolicy: Never
          imagePullSecrets: {{ include "cas-airflow.imagePullSecrets" . | nindent 12 }}
          containers:
            - name: {{ template "cas-airflow.fullname" . }}-test-email-on-failure
              image: artifacts.developer.gov.bc.ca/google-docker-remote/ggl-cas-storage/alpine:3.13.5
              resources:
                requests:
                  cpu: 100m
                  memory: 32Mi
              command: 
                - /usr/bin/env
                - sh
                - -c
                - echo "This CronJob purposely fails, airflow should report an error to ggircs@gov.bc.ca" && exit 1
