apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "cas-airflow.fullname" . }}-test-email-on-failure
  labels:
{{ include "cas-airflow.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-upgrade,pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
{{ include "cas-airflow.labels" . | indent 14 }}
        spec:
          activeDeadlineSeconds: 600
          restartPolicy: Never
          containers:
            - name: {{ template "cas-airflow.fullname" . }}-test-email-on-failure
              image: gcr.io/cas-ggl-storage/alpine:3.13.5
              resources:
                requests:
                  cpu: 100m
                  memory: 32Mi
              command: ["exit"]
              args: ["1"]
