apiVersion: v2
appVersion: 0.0.1
name: cas-airflow
version: 0.0.1
description: Airflow is a platform to programmatically author, schedule and monitor
  workflows
home: https://airflow.apache.org/
icon: https://airflow.apache.org/_images/pin_large.png
sources:
  - https://github.com/bcgov/cas-helm
  - https://airflow.apache.org/
keywords:
  - workflow
  - dag
maintainers:
  - email: alec@button.is
    name: Alec Wenzowski
dependencies:
  - name: airflow
    version: 5.2.5-p3
    repository: "file://../airflow"
