apiVersion: v2
name: cas-airflow
type: application
version: 2.0.18
appVersion: 2.10.5 # The airflow version
description: Helm chart to deploy cas' flavour of airflow, compatible with OpenShift 4. This chart uses the vanilla airflow chart and adds cas' own templates and values.
icon: https://www.astronomer.io/static/airflowNewA.png
keywords:
  - airflow
  - cas
  - ggircs
  - bcgov
dependencies:
  - name: airflow
    version: "1.15.0"
    repository: "https://airflow.apache.org/"
  - name: cas-postgres
    version: "0.9.1"
    repository: https://bcgov.github.io/cas-postgres/
  - name: terraform-bucket-provision
    version: "0.1.3"
    repository: https://bcgov.github.io/cas-pipeline/
