apiVersion: v2
name: cas-airflow
type: application
version: 1.0.3
appVersion: 0.1.1
description: Helm chart to deploy cas' flavour of airflow. This chart uses the vanilla airflow chart and adds cas' own templates and values.
icon: https://www.astronomer.io/static/airflowNewA.png
keywords:
  - airflow
  - cas
  - ggircs
  - bcgov
dependencies:
  - name: airflow
    version: "1.0.0"
    repository: "https://airflow.apache.org/"
  - name: cas-postgres
    version: "0.8.0"
    repository: https://bcgov.github.io/cas-postgres/
