apiVersion: v2
name: cas-airflow
type: application
version: 1.0.11
appVersion: 2.1.2 # The airflow version
description: Helm chart to deploy cas' flavour of airflow, compatible with OpenShift 4. This chart uses the vanilla airflow chart and adds cas' own templates and values.
icon: https://www.astronomer.io/static/airflowNewA.png
keywords:
  - airflow
  - cas
  - ggircs
  - bcgov
dependencies:
  - name: airflow
    version: "1.1.0"
    repository: "https://airflow.apache.org/"
  - name: cas-postgres
    version: "0.8.3"
    repository: https://bcgov.github.io/cas-postgres/
