# Values override for prod namespace
# override example: helm install -f values-prod.yaml -f values.yaml airflow .

airflow:
  uid: 1002500000
  gid: 1002500000

  config:
    logging:
      remote_base_log_folder: gs://0fad32-prod-airflow-logs
    smtp:
      smtp_mail_from: cas-airflow-prod@gov.bc.ca

  workers:
    kubernetes:
      extraVolumeMounts:
        - name: gcs-credentials
          mountPath: /gcs
          readOnly: true
        - name: cas-airflow-dynamic-dags
          mountPath: /opt/airflow/dags/dynamic
      extraVolumes:
        - name: gcs-credentials
          secret:
            secretName: gcp-0fad32-prod-airflow-logs-service-account-key
        - name: cas-airflow-dynamic-dags
          persistentVolumeClaim:
            claimName: cas-airflow-dynamic-dags-pvc

  apiServer:
    extraVolumeMounts:
      - name: gcs-credentials
        mountPath: /gcs
        readOnly: true
    extraVolumes:
      - name: gcs-credentials
        secret:

  dagProcessor:
    env:
      - name: ENVIRONMENT
        value: test
    dagBundleConfigList:
      - name: git-airflow-dags
        classpath: "airflow.providers.git.bundles.git.GitDagBundle"
        kwargs:
          repo_url: "https://github.com/BCgov/cas-airflow.git"
          subdir: "dags"
          tracking_ref: "main"
      - name: git-reg-dags
        classpath: "airflow.providers.git.bundles.git.GitDagBundle"
        kwargs:
          repo_url: "https://github.com/BCgov/cas-registration.git"
          subdir: "dags"
          tracking_ref: "main"
      - name: git-cif-dags
        classpath: "airflow.providers.git.bundles.git.GitDagBundle"
        kwargs:
          repo_url: "https://github.com/BCgov/cas-cif.git"
          subdir: "dags"
          tracking_ref: "main"
      - name: git-data-warehouse-dags
        classpath: "airflow.providers.git.bundles.git.GitDagBundle"
        kwargs:
          repo_url: "https://github.com/BCgov/cas-data-warehouse.git"
          subdir: "dags"
          tracking_ref: "main"
      - name: git-ggircs-dags
        classpath: "airflow.providers.git.bundles.git.GitDagBundle"
        kwargs:
          repo_url: "https://github.com/BCgov/cas-ggircs.git"
          subdir: "dags"
          tracking_ref: "master"
