kind: NetworkSecurityPolicy
apiVersion: security.devops.gov.bc.ca/v1alpha1
metadata:
  name: custom-airflow-intra-release
  labels:
    created-by: {{ .Release.Name }}
spec:
  description: allow everything within this release to communicate
  source:
    - - $namespace={{ .Values.namespaces.airflow }}
      - release={{ .Release.Name }}

  destination:
    - - $namespace={{ .Values.namespaces.airflow }}
      - release={{ .Release.Name }}
