apiVersion: security.devops.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: custom-airflow-scheduler-to-k8s
  labels:
labels: {{ include "cas-airflow.labels" . | nindent 4 }}
spec:
  description: allow service account to run builds/deployments
  source:
    - - $namespace={{ .Release.Namespace }}
      - "@app:k8s:serviceaccountname={{ .Release.Name }}-scheduler"
  destination:
    - - int:network=internal-cluster-api-endpoint
