apiVersion: security.devops.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: custom-airflow-webserver-egress-helm
  labels:
{{ include "cas-airflow.labels" . | nindent 4 }}
spec:
  description: allow webserver to communicate externally
  source:
    - - $namespace={{ .Release.Namespace }}
      - "@app:k8s:serviceaccountname={{ .Release.Name }}-webserver"
  destination:
    - - ext:network=any
