apiVersion: security.devops.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: cas-airflow-webserver-to-k8s
  labels:
{{ include "cas-airflow.labels" . | nindent 4 }}
spec:
  description: allow service account to run builds/deployments
  source:
    - - $namespace={{ .Release.Namespace }}
      - "@app:k8s:serviceaccountname={{ .Release.Name }}-webserver"
  destination:
    - - int:network=internal-cluster-api-endpoint
