apiVersion: security.devops.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: cas-airflow-worker-egress-helm
  labels:
{{ include "cas-airflow.labels" . | nindent 4 }}
spec:
  description: allow worker to communicate externally (to gcp to store logs)
  source:
    - - $namespace={{ .Release.Namespace }}
      - "@app:k8s:serviceaccountname={{ .Release.Name }}-worker"
  destination:
    - - ext:network=any
