apiVersion: batch/v1
kind: Job
metadata:
  name: cas-airflow-cas-shelf-bucket-provider
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  activeDeadlineSeconds: 7200
  template:
    metadata:
      name: cas-airflow-cas-shelf-bucket-provider
    spec:
      containers:
        - name: cas-airflow-cas-shelf-bucket-provider
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          image: docker.pkg.github.com/bcgov/cas-shelf/cas-shelf-tfe-add-app:0.1
          env:
            - name: TFC_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: terraform-cloud-workspace
            - name: TFC_WORKSPACE_ID
              valueFrom:
                secretKeyRef:
                  key: workspace_id
                  name: terraform-cloud-workspace
          command: ["bash",  "/script.sh", {{ .Values.namespace | quote }}, "cas-airflow" ]
      restartPolicy: Never
