version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/stream-minio.tar
          working_directory: ~/app/docker/stream-minio
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/stream-minio.tar | true
          working_directory: ~/app/docker/stream-minio
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=stream-minio -t stream-minio .
          working_directory: ~/app/docker/stream-minio
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/stream-minio.tar stream-minio
          working_directory: ~/app/docker/stream-minio
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/stream-minio.tar
          working_directory: ~/app/docker/stream-minio
      - run:
          name: Test Docker image
          command: |
            CONTEXT="--env DEPTH=2 --env WEBSITE=https://nodejs.org/dist/ --env FILTER=\.png|\.svg --env MINIO_HOST=$MINIO_HOST --env MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY --env MINIO_SECRET_KEY=$MINIO_SECRET_KEY"
            COUNT1=$(docker run -it $CONTEXT stream-minio ./bin/wget-spider.sh | wc -l)
            COUNT2=$(docker run -it $CONTEXT stream-minio ./init.sh tmpproject | grep -c uploading)
            COUNT3=$(docker run -it $CONTEXT stream-minio ./init.sh tmpproject | grep -c skipping)
            if [ COUNT1 -ne COUNT2 ]; then exit 1 fi
          working_directory: ~/app/docker/stream-minio
      # - deploy:
      #     name: Push application Docker image
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         login="$(aws ecr get-login)"
      #         ${login}
      #         docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #         docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #       fi
