version: 2.1

jobs:
  build_docker_image:
    parameters:
      image_name:
        type: string
      cache_version:
        type: integer
        default: 1
    docker:
      - image: docker:19.03-git
    working_directory: ~/cas-airflow/docker/<< parameters.image_name >>
    steps:
      - checkout:
          path: ~/cas-airflow
      - setup_remote_docker
      - restore_cache:
          keys:
            - v<< parameters.cache_version>>-<< parameters.image_name >>-{{ .Branch }}
          paths:
            - /caches/<< parameters.image_name >>.tar
      - run:
          name: Load cache
          command: |
            set +o pipefail
            docker load -i /caches/<< parameters.image_name >>.tar | true
      - run:
          name: Log in to DockerHub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin registry.hub.docker.com
      - run:
          name: Build image
          command: |
            docker build --cache-from=<< parameters.image_name >> -t << parameters.image_name >> .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/<< parameters.image_name >>.tar << parameters.image_name >>
      - save_cache:
          key: v<< parameters.cache_version>>-<< parameters.image_name >>-{{ .Branch }}
          paths:
            - /caches/<< parameters.image_name >>.tar
      - persist_to_workspace:
          root: /caches
          paths:
            - ./<< parameters.image_name >>.tar

  test_stream_minio:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/stream-minio.tar
      - run:
          name: Test Docker image
          environment:
            DEPTH: 2
            WEBSITE: https://nodejs.org/dist/
            FILTER: \.png|\.svg
          command: |
            CONTEXT="--env DEPTH=$DEPTH --env WEBSITE=$WEBSITE --env FILTER=$FILTER --env MINIO_HOST=$MINIO_HOST --env MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY --env MINIO_SECRET_KEY=$MINIO_SECRET_KEY"
            CONTAINER_ID=$(docker run -itd $CONTEXT stream-minio /bin/bash)
            docker exec -it $CONTAINER_ID ./test.sh veryuniquebucket$CIRCLE_WORKFLOW_ID

  deploy_docker_image:
    parameters:
      image_name:
        type: string
      image_tag:
        type: string
    docker:
      - image: docker:19.03-git
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/<< parameters.image_name >>.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            TARGET="docker.pkg.github.com/bcgov/cas-airflow/<< parameters.image_name >>:<< parameters.image_tag >>"
            docker tag << parameters.image_name >> "$TARGET"
            docker push "$TARGET"
          working_directory: ~/cas-airflow/docker/<< parameters.image_name >>

workflows:
  version: 2
  cas-airflow:
    jobs:
      - build_docker_image:
          name: build_docker_<< matrix.image_name >>
          context: cas-pipeline
          matrix:
            parameters:
              image_name: ["cas-airflow", "extract-zips-to-ggircs"]
          filters:
            tags:
              only: /^v.*/
      - deploy_docker_image:
          name: deploy_docker_image_sha1_<< matrix.image_name >>
          matrix:
            parameters:
              image_name: ["cas-airflow", "extract-zips-to-ggircs"]
          image_tag: ${CIRCLE_SHA1}
          requires:
            - build_docker_<< matrix.image_name >>
          filters:
            branches:
              only:
                - develop
                - master
      - deploy_docker_image:
          name: deploy_docker_image_tag_<< matrix.image_name >>
          matrix:
            parameters:
              image_name: ["cas-airflow", "extract-zips-to-ggircs"]
          image_tag: ${CIRCLE_TAG/v/}
          requires:
            - build_docker_<< matrix.image_name >>
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      # TODO: add generic test job to avoid code duplication below
      - build_docker_image:
          name: build_docker_stream-minio
          context: cas-pipeline
          image_name: stream-minio
          filters:
            tags:
              only: /^v.*/
      - test_stream_minio:
          requires:
            - build_docker_stream-minio
          filters:
            tags:
              only: /^v.*/
      - deploy_docker_image:
          name: deploy_docker_image_sha1_stream
          image_name: stream-minio
          image_tag: ${CIRCLE_SHA1}
          requires:
            - test_stream_minio
          filters:
            branches:
              only:
                - develop
                - master
      - deploy_docker_image:
          name: deploy_docker_image_tag_stream-minio
          image_name: stream-minio
          image_tag: ${CIRCLE_TAG/v/}
          requires:
            - test_stream_minio
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
