################################
## Airflow Metadata Secret
#################################
## Uses the PGBOUNCER_URI environment variable to connect to the database, which ensures characters are URI encoded
#################################

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-metadata
  labels:
    release: {{ $.Release.Name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
{{ include "cas-airflow.labels" $ | nindent 4 }}
type: Opaque
data:
  connection: {{ (printf "$PGBOUNCER_URI?sslmode=%s"  .Values.airflow.data.metadataConnection.sslmode) | b64enc | quote }}
