################################
## Airflow Result Backend Secret
#################################
{{- $host := (printf "%s-%s" .Release.Name "patroni") }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-result-backend
  labels:
    release: {{ $.Release.Name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
{{ include "cas-airflow.labels" $ | nindent 4 }}
type: Opaque
data:
  connection: {{ (printf "db+postgresql://%s:%s@%s:%s/%s?sslmode=%s" .Values.airflow.data.resultBackendConnection.user .Values.airflow.data.resultBackendConnection.pass $host (.Values.airflow.data.resultBackendConnection.port | toString) .Values.airflow.data.resultBackendConnection.db .Values.airflow.data.resultBackendConnection.sslmode) | b64enc | quote }}
