################################
## Airflow Result Backend Secret
#################################
## Uses the PGBOUNCER_URI environment variable to connect to the database, which ensures characters are URI encoded
#################################
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-result-backend
  labels:
    release: {{ $.Release.Name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
{{ include "cas-airflow.labels" $ | nindent 4 }}
type: Opaque
data:
  connection: {{ (printf "db+$PGBOUNCER_URI?sslmode=%s"  .Values.airflow.data.resultBackendConnection.sslmode) | b64enc | quote }}
