apiVersion: v2
appVersion: 9.6.10
description: Object-relational database management system (ORDBMS) with an emphasis
  on extensibility and on standards-compliance.
engine: gotpl
home: https://www.postgresql.org/
icon: https://www.postgresql.org/media/img/about/press/elephant.png
keywords:
  - postgresql
  - postgres
  - database
  - sql
maintainers:
  - email: alec@button.is
    name: Alec Wenzowski
name: postgresql
sources:
  - https://github.com/bcgov/cas-helm
  - https://github.com/sclorg/postgresql-container
version: 0.13.1-p4
