# Values override for dev namespace
# override example: helm install -f values-dev.yaml -f values.yaml airflow .

uid: 1002490000
gid: 1002490000

env: 
  - name: "NAMESPACE"
    value: "0fad32-dev"

# Git sync
dags:
  gitSync:
    uid: 1002490000
