# Values
airflowEndpoint: https://cas-airflow-dev.apps.silver.devops.gov.bc.ca
dagId: null
dagConfiguration: "e30K"
helm:
  # hook should be null if the job shouldn't be run as a hook
  hook: "pre-upgrade,pre-install"
  hookWeight: 0
airflowSecret:
  name: airflow-default-user-password
  key: default-user-pass
image:
  repository: ghcr.io/bcgov/cas-airflow-dag-trigger
  tag: ~ # defaults to the chart's version
  pullPolicy: Always
activeDeadlineSeconds: 1200

# The name of the ArtifactoryServiceAccount object created in the cas-provision chart
artifactoryServiceAccount: cas-artifact-download
