# Values
enable: true
airflowEndpoint: https://cas-airflow-dev.apps.silver.devops.gov.bc.ca
dagId: ggircs_cert_renewal
dagConfiguration: "{}"
airflowSecret:
  name: airflow-default-user-password
  key: default-user-pass
image:
  repository: gcr.io/ggl-cas-storage/cas-airflow-dag-trigger
  tag: 0.0.1
  pullPolicy: Always
