{{- if .Values.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cas-airflow-dag-trigger.fullname" . }}
  labels:
{{ include "cas-airflow-dag-trigger.labels" . | indent 4 }}
{{- if .Release.IsUpgrade }}
# This job requires the cas-postgres dependency to be running,
# and is required for the app deployment to become ready.
# Therefore, it needs to be part of the initial install (instead of a pre/post install hook)
# For upgrades, it needs to be a hook so that the delete policy kicks in
# and the previous job template gets deleted (as editing job templates is not allowed)
# It can be a hook during upgrades as the cas-postgres dependency will already be running
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
{{- end }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 1200
  template:
    metadata:
      name: {{ template "cas-airflow-dag-trigger.fullname" . }}
      labels:
{{ include "cas-airflow-dag-trigger.labels" . | indent 8 }}
    spec:
      activeDeadlineSeconds: 1200
      restartPolicy: Never
      containers:
      - name: {{ template "cas-airflow-dag-trigger.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: AIRFLOW_ENDPOINT
            value: {{ .Values.airflowEndpoint }}
          - name: AIRFLOW_USERNAME
            value: cas-airflow-admin
          - name: AIRFLOW_PASSWORD
            valueFrom:
              secretKeyRef:
                key: {{ .Values.airflowSecret.key }}
                name: {{ .Values.airflowSecret.name }}
          - name: RELEASE_SUFFIX
            value: {{ include "cas-airflow-dag-trigger.namespaceSuffix" . }}
        command:
          - /usr/bin/env
          - bash
          - -c
          - ./airflow-dag-trigger.sh {{ .Values.dagId }}
{{- end }}