{{- if .Values.enable }}
apiVersion: batch/v1
kind: Job
metadata:
{{- if .Values.helm.hook }}
  name: {{ template "cas-airflow-dag-trigger.fullname" . }}
{{- else }}
  name: {{ template "cas-airflow-dag-trigger.fullname" . }}-{{ randAlphaNum 5 | lower }}
{{- end }}
  labels:
{{ include "cas-airflow-dag-trigger.labels" . | indent 4 }}
{{- if .Values.helm.hook }}
  annotations:
    "helm.sh/hook": {{ .Values.helm.hook }}
    "helm.sh/hook-weight": {{ .Values.helm.hookWeight | quote }}
{{- end }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
  template:
    metadata:
      name: {{ template "cas-airflow-dag-trigger.fullname" . }}
      labels:
{{ include "cas-airflow-dag-trigger.labels" . | indent 8 }}
    spec:
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      restartPolicy: Never
      containers:
      - name: {{ template "cas-airflow-dag-trigger.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: AIRFLOW_ENDPOINT
            value: {{ .Values.airflowEndpoint }}
          - name: AIRFLOW_USERNAME
            value: cas-airflow-admin
          - name: AIRFLOW_PASSWORD
            valueFrom:
              secretKeyRef:
                key: {{ .Values.airflowSecret.key }}
                name: {{ .Values.airflowSecret.name }}
          - name: RELEASE_SUFFIX
            value: {{ include "cas-airflow-dag-trigger.namespaceSuffix" . }}
        command:
          - /usr/bin/env
          - bash
          - -c
          - ./airflow-dag-trigger.sh {{ .Values.dagId }} {{ .Values.dagConfiguration | default "{}" | quote }}
{{- end }}
