{{- if .Values.airflow.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-patroni-policy
  labels:
    tier: airflow
    component: airflow-webserver-policy
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-patroni
  policyTypes:
  - Ingress
  ingress:
  - from:
    podSelector:
      matchLabels:
        tier: airflow
        release: {{ .Release.Name }}
        component: scheduler
    podSelector:
      matchLabels:
        tier: airflow
        release: {{ .Release.Name }}
        component: webserver
{{- end }}
