{{- range (list .Values.namespaces.airflow .Values.namespaces.ggircs) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ . }}
  name: {{ $.Release.Name }}-airflow-worker-rolebinding
  labels:
    release: {{ $.Release.Name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
labels: {{ include "cas-airflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cas-provision-job-runner
subjects:
  - kind: ServiceAccount
    name: {{ $.Release.Name }}-worker
    namespace: {{ $.Release.Namespace }}

{{- end }}
