{{- if .Values.gcpLogsUpload.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cas-airflow.fullname" . }}-logs-upload-bucket-provider
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  activeDeadlineSeconds: 1200
  template:
    metadata:
      name: {{ template "cas-airflow.fullname" . }}-logs-upload-bucket-provider
      labels: {{ include "cas-airflow.labels" . | nindent 8 }}
    spec:
      imagePullSecrets: {{ include "cas-airflow.imagePullSecrets" . | nindent 8 }}
      containers:
        - name: {{ template "cas-airflow.fullname" . }}-logs-upload-bucket-provider
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          image: {{ .Values.gcpLogsUpload.image.casShelf.repository }}:{{ .Values.gcpLogsUpload.image.casShelf.tag }}
          imagePullPolicy: {{ .Values.gcpLogsUpload.image.casShelf.pullPolicy }}
          env:
            - name: TFC_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: terraform-cloud-workspace
            - name: TFC_WORKSPACE_ID
              valueFrom:
                secretKeyRef:
                  key: workspace_id
                  name: terraform-cloud-workspace
          command: ["bash",  "/script.sh", {{ .Release.Namespace | quote }}, {{ .Values.gcpLogsUpload.bucketSuffix | quote }}]
      restartPolicy: Never
{{- end }}
