name: Build CAS Airflow DAG trigger Container with chart tag

on:
  tags:
    - "cas-airflow-dag-trigger-*"

jobs:
  cas-airflow-dag-trigger-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the tag name
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCR_KEY }}
          project_id: ggl-cas-storage
          image_name: cas-airflow-dag-trigger
          image_tag: latest,${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}
          dockerfile: dag-trigger/Dockerfile
          context: dag-trigger
