name: Build Containers on chart release

on:
  release:
    types: [created, published]

jobs:
  cas-airflow-build:
    if: startsWith(github.ref, 'refs/tags/cas-airflow-2') # this will need to be updated if do a major release of the chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the tag name
        id: get_tag_name
        run: echo ::set-output name=CHART_VERSION::${GITHUB_REF/refs\/tags\/cas-airflow-/}
      - uses: ./.github/actions/build-image
        with:
          image_name: cas-airflow
          context: .
          dockerfile_path: Dockerfile
          github_token: ${{ secrets.GITHUB_TOKEN }}
          chart_version: ${{ steps.get_tag_name.outputs.CHART_VERSION }}
          is_chart_release: true
  cas-airflow-dag-trigger-build:
    if: startsWith(github.ref, 'refs/tags/cas-airflow-dag-trigger-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the tag name
        id: get_tag_name
        run: echo ::set-output name=CHART_VERSION::${GITHUB_REF/refs\/tags\/cas-airflow-dag-trigger-/}
      - uses: ./.github/actions/build-image
        with:
          image_name: cas-airflow-dag-trigger
          context: dag-trigger
          dockerfile_path: dag-trigger/Dockerfile
          github_token: ${{ secrets.GITHUB_TOKEN }}
          chart_version: ${{ steps.get_tag_name.outputs.CHART_VERSION }}
          is_chart_release: true
