name: Build Containers on chart release

on:
  release:
    types: [created]

jobs:
  cas-airflow-build:
    if: startsWith(github.ref, 'refs/tags/cas-airflow-1') # this will need to be updated if do a major release of the chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the tag name
        id: get_tag_name
        run: echo ::set-output name=CHART_VERSION::${GITHUB_REF/refs\/tags\/cas-airflow-/}
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1.0
        with:
          gcloud_service_key: ${{ secrets.GCR_KEY }}
          project_id: ggl-cas-storage
          image_name: cas-airflow
          image_tag: latest,${{ steps.get_tag_name.outputs.CHART_VERSION }}
  cas-airflow-dag-trigger-build:
    if: startsWith(github.ref, 'refs/tags/cas-airflow-dag-trigger-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the tag name
        id: get_tag_name
        run: echo ::set-output name=CHART_VERSION::${GITHUB_REF/refs\/tags\/cas-airflow-dag-trigger-/}
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1.0
        with:
          gcloud_service_key: ${{ secrets.GCR_KEY }}
          project_id: ggl-cas-storage
          image_name: cas-airflow-dag-trigger
          image_tag: latest,${{ steps.get_tag_name.outputs.CHART_VERSION }}
          dockerfile: dag-trigger/Dockerfile
          context: dag-trigger
