name: Build dag-trigger on release

on:
  push:
    branches:
      - main
    tags:
      - cas-airflow-dag-trigger-.*

jobs:
  cas-airflow-dag-trigger-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the tag name
        id: get_tag_name
        run: echo ::set-output name=CHART_VERSION::${GITHUB_REF/refs\/tags\/cas-airflow-dag-trigger-/}
      - uses: ./.github/actions/build-image
        with:
          image_name: cas-airflow-dag-trigger
          context: dag-trigger
          dockerfile_path: dag-trigger/Dockerfile
          github_token: ${{ secrets.GITHUB_TOKEN }}
          chart_version: ${{ steps.get_tag_name.outputs.CHART_VERSION }}
          is_chart_release: true
